import{a as S,S as v,i as a}from"./assets/vendor-B5nsgUv9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const q="https://pixabay.com/api/",R="54799522-83001b78b1b469e44ac3f4ab2";async function y(r,e){const i={key:R,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await S.get(q,{params:i})).data}const m=document.querySelector(".loader"),h=document.querySelector(".load-more-container");let E=new v(".gallery-link",{captionsData:"alt",captionDelay:250});function g(){m.classList.remove("is-hidden")}function b(){m.classList.add("is-hidden")}function L(){h.classList.remove("is-hidden")}function u(){h.classList.add("is-hidden")}function x(r){r.innerHTML=""}function w(r,e){const i=r.map(o=>`
       <li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p class="info-text"><b>Likes</b> ${o.likes}</p>
          <p class="info-text"><b>Views</b> ${o.views}</p>
          <p class="info-text"><b>Comments</b> ${o.comments}</p>
          <p class="info-text"><b>Downloads</b> ${o.downloads}</p>
        </div>
      </li>`).join("");e.insertAdjacentHTML("beforeend",i),E.refresh()}const p=document.querySelector(".form"),P=document.querySelector("input"),f=document.querySelector(".gallery"),d=document.querySelector(".load-btn");let n=1,l="";p.addEventListener("submit",async r=>{if(r.preventDefault(),l=P.value.trim(),l==="")return a.error({title:"Error",message:"Sorry, you need to enter a request!",position:"topRight"});x(f),u(),g(),n=1;try{const e=await y(l,n);if(e.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}w(e.hits,f),e.totalHits>15?L():e.totalHits>0&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{a.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{b(),p.reset()}});d.addEventListener("click",async()=>{n++,d.disabled=!0,u(),g();try{const r=await y(l,n);w(r.hits,f);const e=document.querySelector(".gallery-item");if(e){const i=e.getBoundingClientRect().height;window.scrollBy({left:0,top:i,behavior:"smooth"})}n*15>=r.totalHits?(u(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{b(),d.disabled=!1}});
//# sourceMappingURL=index.js.map
