import{a as w,S,i}from"./assets/vendor-B5nsgUv9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const v="https://pixabay.com/api/",q="54799522-83001b78b1b469e44ac3f4ab2";async function m(r,e){const a={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await w.get(v,{params:a})).data}const p=document.querySelector(".loader"),y=document.querySelector(".load-more-container");let x=new S(".gallery-link",{captionsData:"alt",captionDelay:250});function g(){p.classList.remove("is-hidden")}function h(){p.classList.add("is-hidden")}function P(){y.classList.remove("is-hidden")}function b(){y.classList.add("is-hidden")}function B(r){r.innerHTML=""}function L(r,e){const a=r.map(o=>`
       <li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p class="info-text"><b>Likes</b> ${o.likes}</p>
          <p class="info-text"><b>Views</b> ${o.views}</p>
          <p class="info-text"><b>Comments</b> ${o.comments}</p>
          <p class="info-text"><b>Downloads</b> ${o.downloads}</p>
        </div>
      </li>`).join("");e.insertAdjacentHTML("beforeend",a),x.refresh()}const f=document.querySelector(".form"),E=document.querySelector("input"),u=document.querySelector(".gallery"),d=document.querySelector(".load-btn");let n=1,l="";f.addEventListener("submit",async r=>{if(r.preventDefault(),l=E.value.trim(),l==="")return i.error({message:"Sorry..."});B(u),b(),g(),n=1;try{const e=await m(l,n);if(e.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(e.hits,u),e.totalHits>15&&P()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{h(),f.reset()}});d.addEventListener("click",async()=>{n++,d.disabled=!0,g();try{const r=await m(l,n);L(r.hits,u);const e=document.querySelector(".gallery-item");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a,behavior:"smooth"})}n*15>=r.totalHits&&(b(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{h(),d.disabled=!1}});
//# sourceMappingURL=index.js.map
